# Generated by Django 5.2.6 on 2025-09-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('classe', models.CharField(max_length=50)),
                ('club', models.CharField(choices=[('club1', 'Club1'), ('club2', 'Club2'), ('club3', 'Club3')], max_length=10)),
                ('theme', models.CharField(choices=[('theme1', 'Thème 1'), ('theme2', 'Thème 2'), ('theme3', 'Thème 3')], max_length=10)),
            ],
        ),
    ]
