# Generated by Django 5.2.6 on 2025-09-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='niveau',
            field=models.CharField(blank=True, choices=[('6', 'Niveau 6'), ('5', 'Niveau 5'), ('4', 'Niveau 4'), ('3', 'Niveau 3')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='classe',
            field=models.CharField(choices=[('a', 'Classe A'), ('b', 'Classe B'), ('c', 'Classe C'), ('d', 'Classe D'), ('e', 'Classe E'), ('f', 'Classe F')], max_length=1),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='club',
            field=models.CharField(choices=[('club1', 'Web'), ('club2', 'Echec'), ('club3', 'Théatre')], max_length=10),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='theme',
            field=models.CharField(choices=[('theme1', 'Créer des sites web'), ('theme2', 'Coder des jeux'), ('theme3', 'Utiliser GPT')], max_length=10),
        ),
    ]
