# Generated by Django 5.2.6 on 2025-09-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_etudiant_niveau_alter_etudiant_classe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='classe',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D'), ('e', 'E'), ('f', 'F')], max_length=1),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='niveau',
            field=models.CharField(blank=True, choices=[('6', '6'), ('5', '5'), ('4', '4'), ('3', '3')], max_length=1, null=True),
        ),
    ]
