# Generated by Django 5.2.6 on 2025-09-29 07:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_alter_etudiant_classe_alter_etudiant_niveau'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='date_inscription',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
