# Generated by Django 5.2.6 on 2025-09-29 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_etudiant_date_inscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='cours_suivi',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='date_presence',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='date_inscription',
            field=models.DateField(auto_now_add=True),
        ),
    ]
