# Generated by Django 5.2.6 on 2025-10-10 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_etudiant_cours_suivi_etudiant_date_presence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('1', 'Claviers'), ('2', 'Naviguation'), ('3', 'Lecture'), ('4', 'Programmation'), ('5', 'Création')], max_length=1, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='etudiant',
            name='objectif',
            field=models.TextField(blank=True, null=True),
        ),
    ]
