# Generated by Django 5.2.6 on 2025-10-10 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0006_niveau_etudiant_objectif'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Niveau',
        ),
        migrations.AddField(
            model_name='etudiant',
            name='skill',
            field=models.CharField(blank=True, choices=[('1', 'Claviers'), ('2', 'Naviguation'), ('3', 'Lecture'), ('4', 'Programmation'), ('5', 'Création')], max_length=1, null=True),
        ),
    ]
